server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:studentDb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
