server:
  port: 8888

spring:
  profiles:
    active: native
  aplication:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
